// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnFDlyT_ipPJqsMtPbkMz_STDZzXTidvo',
    appId: '1:375355935948:web:3262a0abb1d0687da4c669',
    messagingSenderId: '375355935948',
    projectId: 'permataxkmr',
    authDomain: 'permataxkmr.firebaseapp.com',
    storageBucket: 'permataxkmr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsbY4ZTv_QnBEf5U6o70cqaZu7Q9YQX7E',
    appId: '1:375355935948:android:3b92aad41f7592ffa4c669',
    messagingSenderId: '375355935948',
    projectId: 'permataxkmr',
    storageBucket: 'permataxkmr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAseZl0Hw7Zj8_Lq0jsfhJtgD9ZyGTacAY',
    appId: '1:375355935948:ios:2c0564d3f504d423a4c669',
    messagingSenderId: '375355935948',
    projectId: 'permataxkmr',
    storageBucket: 'permataxkmr.appspot.com',
    iosBundleId: 'com.example.test1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAseZl0Hw7Zj8_Lq0jsfhJtgD9ZyGTacAY',
    appId: '1:375355935948:ios:de022de57e85f5fea4c669',
    messagingSenderId: '375355935948',
    projectId: 'permataxkmr',
    storageBucket: 'permataxkmr.appspot.com',
    iosBundleId: 'com.example.test1.RunnerTests',
  );
}
